enum class TeeKOCharacterName(val str: String) {
    CATFISH("catfish"),
    CAT("cat"),
    KAPPA("kappa"),
    RED_DEMON("red_demon"),
    HAIR("hair"),
    FIRE("fire"),
    CROW("crow"),
    BLUE_DEMON("blue_demon"),
    FOX("fox"),
    BUN("bun"),
    RACCOON("raccoon"),
    DOG("dog"),
    SNAKE("snake"),
    MONKEY("monkey"),
    UMBRELLA("umbrella"),
    BAKU("baku"),
}
